version: '3.1'

services:

  ui:
    build: ./ui
    image: ui:latest
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - nat

  api:
    build: ./api
    image: api:latest
    ports:
      - 8081:80
    depends_on:
      - database
    networks:
      - nat

  database:
    build: ./database
    image: mssql:latest
    environment:
      - ACCEPT_EULA=Y 
      - sa_password=P@ssw0rd
    networks:
      - nat

networks:
  nat:
    external: true
